### ISSUE TITLE
antivirus

### ISSUE THREAD

**Issue by GabrielPenCatherineIsSpying** [vialonitasuhardiman/antivirus#1]
Hi Gabriel, this is Catherine Tan. I’m reaching out because my computer is in rough shape—it's made out of toilet paper, with a cardboard CPU and a plastic processor. On top of that, my antivirus isn’t working well. Can you recommend a reliable antivirus solution for me?

**Comment by vialonitasuhardiman** [comment]
Malwarebytes, also this is github, if you do it in other community, you might be flagged as spam, and possibly roasted.
